version: "3.5"

services:
  sonarqube:
    image: sonarqube:7.9.5-community
    container_name: sonarqube
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - ./extensions/sonarqube-community-branch-plugin-1.3.2.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
      - ./extensions/sonarqube-community-branch-plugin-1.3.2.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar

  db:
    image: postgres:11-alpine
    container_name: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
networks:
  sonarnet:
    driver: bridge
